name: 'C++ CI'

on:
  push:
    tags:
      - v*
    branches:
      - 'hw5'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Install minimal dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            cmake \
            build-essential \
            doxygen graphviz  plantuml
      
      - name: Configure CMake
        working-directory: ./hw5/editor
        run: cmake -DCMAKE_BUILD_TYPE=Release -DPATCH_VERSION=${{ github.run_number }} .
      
      - name: Build
        working-directory: ./hw5/editor
        run: cmake --build . --parallel
      
      - name: Run tests
        working-directory: ./hw5/editor
        run: ctest --output-on-failure --parallel 4
      
      - name: Package
        working-directory: ./hw5/editor
        run: cmake --build . --target package --parallel
      
      - name: Create Release and Upload Asset
        run: |
          FILE_PATH="./hw5/editor/editor-0.5.${{ github.run_number }}-Linux.deb"
          [ ! -f "$FILE_PATH" ] && { echo "Error: File $FILE_PATH not found!"; exit 1; }
          gh release create "v0.5.${{ github.run_number }}" \
            --title "Release v0.5.${{ github.run_number }}" \
            --draft=false \
            --prerelease=false \
            --notes "" \
            "$FILE_PATH"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Doxygen HTML
        run: |
          cd hw5/editor
          mkdir -p docs/html
          sed -i 's|OUTPUT_DIRECTORY\s*=\s*.*|OUTPUT_DIRECTORY = ./docs|' Doxyfile
          sed -i 's|HTML_OUTPUT\s*=\s*.*|HTML_OUTPUT = html|' Doxyfile
          doxygen Doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./hw5/editor/docs/html
          destination_dir: hw5
          keep_files: true
