name: 'C++ CI'

on:
  push:
    tags:
      - v*
    branches:
      - 'hw4'

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            build-essential \
            doxygen \
            graphviz
      
      - name: Configure CMake
        working-directory: ./hw4/print_ip
        run: cmake . -DPATCH_VERSION=${{ github.run_number }}
      
      - name: Build
        working-directory: ./hw4/print_ip
        run: cmake --build .
      
      - name: Run tests
        working-directory: ./hw4/print_ip
        run: ctest --output-on-failure
      
      - name: Package
        working-directory: ./hw4/print_ip
        run: cmake --build . --target package
      
      - name: Create Release and Upload Asset
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --draft=false \
            --prerelease=false \
            ./hw4/print_ip/print_ip-0.4.${{ github.run_number }}-Linux.deb \
            --name "print_ip-0.4.${{ github.run_number }}-Linux.deb" \
            --content-type "application/vnd.debian.binary-package"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Doxygen HTML
        run: |
          cd hw4/print_ip
          mkdir -p docs/html  # create dir
          doxygen Doxyfile    # gen docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./hw4/print_ip/docs/html  # path
          keep_files: false         # not clear