name: 'C++ CI'

on:
  push:
    tags:
      - v*
    branches:
      - 'hw4'

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      
      # Кеширование APT пакетов
      - name: Cache APT packages
        uses: actions/cache@v3
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-
      
      # Установка только необходимых зависимостей
      - name: Install minimal dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            cmake build-essential \
            doxygen graphviz plantuml

      # Кеширование сборки проекта
      - name: Cache project build
        uses: actions/cache@v3
        with:
          path: |
            ./hw4/print_ip/build
            ./hw4/print_ip/CMakeCache.txt
          key: ${{ runner.os }}-build-${{ github.sha }}-${{ github.run_number }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.sha }}-
            ${{ runner.os }}-build-
      
      - name: Create build directory
        working-directory: ./hw4/print_ip
        run: mkdir -p build
      
      - name: Configure CMake
        working-directory: ./hw4/print_ip/build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DPATCH_VERSION=${{ github.run_number }} ..
      
      - name: Build
        working-directory: ./hw4/print_ip/build
        run: cmake --build . --parallel
      
      - name: Package
        working-directory: ./hw4/print_ip/build
        run: cmake --build . --target package --parallel
      
      - name: Create Release and Upload Asset
        run: |
          FILE_PATH="./hw4/print_ip/build/print_ip-0.4.${{ github.run_number }}-Linux.deb"
          [ ! -f "$FILE_PATH" ] && { echo "Error: File $FILE_PATH not found!"; exit 1; }
          gh release create "v0.4.${{ github.run_number }}" \
            --title "Release v0.4.${{ github.run_number }}" \
            --draft=false \
            --prerelease=false \
            --notes "" \
            "$FILE_PATH"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Doxygen HTML
        working-directory: ./hw4/print_ip
        run: |
          mkdir -p docs/html
          sed -i 's|OUTPUT_DIRECTORY\s*=\s*.*|OUTPUT_DIRECTORY = ./docs|' Doxyfile
          sed -i 's|HTML_OUTPUT\s*=\s*.*|HTML_OUTPUT = html|' Doxyfile
          doxygen Doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./hw4/print_ip/docs/html
          destination_dir: hw4
          force_orphan: false #true  # Это полностью очистит ветку перед развертыванием
          keep_files: true #false
          
